from __future__ import annotations

CONFIG_FILE = "config.json"
RUNTIME_OVERRIDES_FILE = "runtime_overrides.json"


DEFAULT_CONFIG: dict = {
    "strategy": {"name": "daily_trend_reversal"},
    "daily_trend_reversal": {
        "trend_ma_days": 200,
        "reversal_mode": "atr",
        "reversal_threshold_pct": 2.0,
        "reversal_threshold_atr": 0.1,
        "reversal_lookback_days": 1,
        "reversal_quantile": 0.35,
        "reversal_quantile_lookback_days": 30,
        "entry_time_et": "09:35",
        "entry_start_et": "09:35",
        "entry_end_et": "11:30",
        "session_open_et": "09:30",
        "entry_price_mode": "open",
        "use_intraday_entry": True,
        "intraday_entry_in_watchlist": False,
        "max_positions": 0,
        "risk_per_trade": 0.02,
        "leverage": 4.0,
        "max_margin_usage": 0.75,
        "margin_safety_buffer": 0.25,
        "per_trade_max_pct_available": 0.25,
        "equal_split_across_max_slots": False,
        "min_available_funds_abs": 0.0,
        "min_available_funds_ratio_of_netliq": 0.0,
        "starting_equity": 30000.0,
        "minute_report_enabled": True,
        "minute_report_interval_sec": 60,
        "minute_report_max_symbols": 20,
        "minute_report_lookback_minutes": 5,
        "stop_mode": "atr",
        "atr_period": 14,
        "stop_atr_mult": 1.0,
        "stop_pct": 1.0,
        "target_rr": 1.5,
        "stop_r": 1.0,
        "target_r": 1.5,
        "time_exit_days": 2,
        "time_stop_minutes": 90,
        "intraday_only": False,
        "intraday_filter_enabled": False,
        "intraday_filter_require_bars": False,
        "intraday_filter_apply_in_watchlist": False,
        "min_gap_bps_long": 0.0,
        "min_gap_bps_short": 0.0,
        "early_range_minutes": 0,
        "max_early_pullback_bps": 0.0,
        "session_close_et": "16:00",
        "flatten_buffer_minutes": 5,
        "trend_fast_len": 0,
        "trend_slow_len": 0,
        "trend_min_slope_bps": 0,
        "trend_min_distance_atr": 0.0,
        "volume_lookback_days": 60,
        "volume_min_ratio": 0.0,
        "entry_order_type": "market",
        "order_tif": "day",
        "use_brackets": True,
        "fixed_qty": None,
    },
    "watchlist": {
        "lookback_days": 252,
        "minTrades": 30,
        "reject_negative_pnl": True,
        "minProfitFactor": 1.05,
        "minAvgR": 0.0,
        "top_k": 0,
    },
    "watchlist_report_enabled": False,
    "watchlist_source": "node",
    "watchlist_node_base": "http://localhost:3000",
    "watchlist_asset_filters": {
        "asset_class": "us_equity",
        "status": "active",
        "price_min": 15,
        "price_max": 1000,
        "max_spread_bps_median": 10,
        "shortable": True,
        "marginable": True,
        "easy_to_borrow": True,
        "tradable": True,
    },
    "alpaca": {
        "base_url": "https://paper-api.alpaca.markets",
        "data_url": "https://data.alpaca.markets",
        "api_key_id": "",
        "api_secret_key": "",
        "data_feed": "iex",
        "bars_chunk_size": 50,
        "adjustment": "raw",
        "timeout_sec": 30,
        "max_retries": 3,
        "retry_backoff_sec": 2,
    },
    "replay": {
        "enabled": False,
        "start_date": None,
        "end_date": None,
        "emit_daily_details": False,
    },
    "daily_bars_cache_dir": "alpaca-ohlc",
    "minute_bars_cache_dir": "cache/ohlc_minute",
    "minute_bars_refresh": False,
    "watchlists_dir": "watchlists",
    "logs_dir": "logs",
    "symbols": [],
}
